import { Script } from '@script_types/script/script';
import { ScriptConfig } from '../gen/spec_config'; /* File will be automatically generated by compiler! Run "nom run cli install" */
import { specification } from './spec';
import { Instance } from './main';

export class MyScript implements Script.Class<ScriptConfig> {
    
   private instance: Instance | undefined;

  start = async (ctx: Script.Context, config: ScriptConfig): Promise<void> => {
        this.instance = new Instance(ctx, config);

        console.info("Ident:" + specification.id_ident);
        console.info("Config:", config);

        return this.instance.start(); // return the start promise
    }

    stop = async (reason: Script.StopReason): Promise<void> => {
        await this.instance?.stop(reason);
    }
}

export const script = new MyScript();